### PR TITLE
fix for mixed language media with transcripts

### LINKED ISSUE #2293: second language video switching
When choosing a second language on a video, it will stay in the transcript sidebar until you choose a new language. https://sul-purl-stage.stanford.edu/ws924ny0572

https://github.com/user-attachments/assets/a65470ae-b166-4662-85b5-419251fc51ab

### PR DESCRIPTION
**Pull request by dnoneill**
closes #2293

### CODE REVIEW

**Comment by dnoneill** [comment]
This doesn't work on safari. I am working on it.

File: app/javascript/controllers/transcript_controller.js [hunk 1]
```diff
@@ -89,6 +89,8 @@ export default class extends Controller {
     // changing disabled mode to "hidden" to prevent losing cue information.
     if(videojs.browser.IS_ANY_SAFARI) {
       this.convertDisabledTracks()
+      // track.cues returns 0 in safari, even when there are cues
```
Comment (jcoyne) [inline app/javascript/controllers/transcript_controller.js:92]: I'm not sure why this is relevant.  Is there more to context you can pass on here?

Comment (dnoneill) [reply app/javascript/controllers/transcript_controller.js:92]: Sure. I can update the comment, the long and short is if there are two vtt files with captions, return captions.filter(track => this.trackCues(track).length) returns a list of one file. This has to do with something weird in safari that returns track.cues.length == 0, on hidden tracks.

**Review by corylown — APPROVED** [review]
