### PR TITLE
Intercept links from IIIF manifest to set target and rels

### LINKED ISSUE #1963: Don't try to open links within the embed viewer
### Expected behavior
Links within the embedded player should be opened in a new tab.

### Actual behavior
On Firefox, at least, the browser tries to open links inside the viewer itself. 

On purl.stanford.edu, this leads to getting a purl page inside the viewer:

> Screenshot 2023-12-11 at 9 07 28 PM

On another domain, this leads to an error within the viewer:

> Screenshot 2023-12-11 at 9 10 00 PM

### Steps to reproduce the behavior

1. Open a media item in purl and a non-purl website like
  - Purl: https://purl.stanford.edu/bd699ky6829  
  - SW: https://searchworks.stanford.edu/view/14803920
2. Open the Info panel.
3. Click on the purl link

### Browser / Environment
Firefox 120.0.1 on MacOS Ventura

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes #1963

Links from the IIIF manifest, such as for "Available Online" in the metadata panel, are generated in PURL without targets or rels, and as such, these links wind up opening inside the embed iframe leading to a dizzying link-ception scenario as documented in the associated issue. This commit fixes that behavior in the same way Mirador already does: https://github.com/ProjectMirador/mirador/blob/cefe7b7b520ae1cb637d935c7b3cfceaff96b14a/src/components/SanitizedHtml.js#L17-L25 Namely, by sniffing each IIIF manifest value to see if it is a node with a target, such as an anchor element, and coercing the target to "_blank" and setting the expected rels. This forces links to open in a new window.

### CODE REVIEW

File: app/components/embed/media_with_companion_windows_component.rb [hunk 1]
```diff
@@ -23,7 +23,7 @@ def resources_with_primary_file
     end
 
     def iiif_v3_manifest_url
-      "#{Settings.purl_url}/#{druid}//iiif3/manifest"
+      "#{Settings.purl_url}/#{druid}/iiif3/manifest"
```
Comment (mjgiarlo) [inline app/components/embed/media_with_companion_windows_component.rb:26]: Typo fix. Functionally equivalent to what was here before.

File: app/javascript/controllers/media_tag_controller.js [hunk 2]
```diff
@@ -25,7 +25,7 @@ export default class extends Controller {
 
   dispatchManifestEvent(json) {
     const event = new CustomEvent('iiif-manifest-received', { detail: json })
-    window.dispatchEvent(event)  
+    window.dispatchEvent(event)
```
Comment (mjgiarlo) [inline app/javascript/controllers/media_tag_controller.js:28]: Ditch trailing whitespace. (My editor did this.)

**Review by jcoyne — APPROVED** [review]
