### PR TITLE
Render video tags for Safari when an audio has captions

### LINKED ISSUE #1635: I do not see captions displayed for test audio object when using Safari Version 16.6 (18615.3.12.11.2)
### Expected behavior
I have selected to display english captions and expect to see captions display in the media player. Note that there are no reported issues with displaying captions for this test audio object in Chrome or Firefox. 

### Actual behavior
No captions display when english captions are selected.

### Steps to reproduce the behavior
Open https://sul-purl-stage.stanford.edu/xs884bk3832 in Safari

### Browser / Environment
Safari Version 16.6 (18615.3.12.11.2)

### PR DESCRIPTION
**Pull request by jcoyne**
Because Safari 16.6 doesn't show captions on an audio

Fixes #1635

### CODE REVIEW

File: test/components/previews/embed/media_with_companion_windows_component_preview.rb [hunk 1]
```diff
@@ -6,7 +6,7 @@
 module Embed
   class MediaWithCompanionWindowsComponentPreview < ViewComponent::Preview
     def with_audio
-      embed_request = Embed::Request.new(url: 'https://purl.stanford.edu/bb169jj6514')
+      embed_request = Embed::Request.new(url: 'https://purl.stanford.edu/gj753wr1198')
```
Comment (jcoyne) [inline test/components/previews/embed/media_with_companion_windows_component_preview.rb:9]: This one has a vtt track, so it's a more useful case.

**Review by mjgiarlo — APPROVED** [review]
