### PR TITLE
Add tests and fix embed issue in multiple contexts

### LINKED ISSUE #881: New version of embed code returns non-functional iframe
### Expected behavior
A user should be able to copy the embed code from the UV and embed it in a website to get a functional iframe

### Actual behavior
See below, but current embed code produces an error "The page you were looking for doesn't exist"

### Steps to reproduce the behavior
See detailed email below from external user

### Browser / Environment
Chrome (tested by me), not sure about external user.

### User feedback

The embed code for https://purl.stanford.edu/ch403gv9140
does not load.
Here's the code that I'm copying and pasting to our website:
`<iframe src="https://embed.stanford.edu/uv.html#?manifest=https://purl.stanford.edu/ch403gv9140/iiif/manifest&c=0&m=0&s=0&cv=0&config=./uv-config.json&locales=en-GB:English (GB)&xywh=-922,-53,2527,1044&r=0" width="560" height="420" allowfullscreen frameborder="0"></iframe>`

The code above generates an error message that says 

"The page you were looking for doesn't exist. You may have mistyped the address or the page may have moved. If you are the application owner check the logs for more information."

However, if I remove sections of the URL and replace it with the following, the iframe loads correctly.
`<iframe src="https://embed.stanford.edu/iframe?url=https://purl.stanford.edu/ch403gv9140" width="560" height="420" allowfullscreen frameborder="0"></iframe>
`
The code above is what that I pulled from Batch 1, in early March for Loretta Argrett: https://purl.stanford.edu/vb049xq7502. The Iframe for this particular example is much simpler. I've notice that the code for Loretta Argrett has changed in Batch2. 

So is this a bug or is can you advise on the best to make this iframe loadable onto other websites?

The web page below further illustrates the non working links vs the working links:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <iframe src="https://embed.stanford.edu/uv.html#?manifest=https://purl.stanford.edu/ch403gv9140/iiif/manifest&c=0&m=0&s=0&cv=0&config=./uv-config.json&locales=en-GB:English (GB)&xywh=-796,0,2274,939&r=0" width="560" height="420" allowfullscreen frameborder="0"></iframe><br>https://purl.stanford.edu/ch403gv9140 Klein<br>
  <iframe src="https://embed.stanford.edu/uv.html#?manifest=https://purl.stanford.edu/vb049xq7502/iiif/manifest&c=0&m=0&s=0&cv=0&config=./uv-config.json&locales=en-GB:English (GB)&xywh=-15,-146,379,574&r=0" width="560" height="420" allowfullscreen frameborder="0"></iframe><br>https://purl.stanford.edu/vb049xq7502 Argrett<br>
  <iframe width="560" height="420" src="https://embed.stanford.edu/iframe?url=https://purl.stanford.edu/vb049xq7502" allowfullscreen="allowfullscreen" frameborder="0"></iframe><br>https://purl.stanford.edu/vb049xq7502 Argrett<br>
  <iframe src="https://embed.stanford.edu/iframe?url=https://purl.stanford.edu/ch403gv9140" width="560" height="420" allowfullscreen frameborder="0"></iframe><br>https://purl.stanford.edu/vb049xq7502 Klein<br>
</body>
</html>
```

With the following result:

screencapture-2018-04-27

### PR DESCRIPTION
**Pull request by mejackreed**
Changes made in https://github.com/sul-dlss/universalviewer/pull/60 and added here.

Fixes #881 

The problem with our original fix was that UV returns a different URL to be embedded depending on the context it is in. Our first fix didn't account for the context of a page using oembed to embed directly (we were only testing and looking at it from the `/iframe` route directly.

To test locally, load an image object from the sandbox `http://127.0.0.1:3000/pages/sandbox`.

Deployed for testing on uat https://sul-purl-uat.stanford.edu/vb049xq7502

### CODE REVIEW

File: spec/features/uv_spec.rb [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+    before do
+      stub_purl_response_with_fixture(image_with_pdf_purl)
+      visit_iframe_response('bb023ts9016')
+    end
+    it 'has an embeddable iframe' do
+      find('button.share').click
+      expect(page).to have_css '.embedView', visible: true
+      expect(page).to have_field(
+        '.code',
+        with: /<iframe src="http:\/\/127.0.0.1:\d+\/iframe\?url=https:\/\/purl.stanford.edu\/bb023ts9016" width="560" height="420" allowfullscreen frameborder="0"><\/iframe>/,
```
Comment (mejackreed) [inline spec/features/uv_spec.rb]: Everything works up until here.

**Comment by camillevilla** [comment]
Looks good to me! It would also be good to ticket that pending test.
