### PR TITLE
show pdf location restriction banner per file

### LINKED ISSUE #2360: Location-restricted PDFs do not display in the PDF viewer even at an authorized location
**Describe the bug**

When at an authorized location, location-restricted PDFs do not open in the viewer. It is possible to download the PDFs from direct links to the Stacks URL but the viewer presentation looks the same as when you are not in an authorized location.

I tested this while on campus visiting the Special Collections reading room. Geoff Willard (@oceanofsound ) also verified this from his workstation that is authorized to view location-restricted materials.

**Expected behavior**

When at an authorized location, the viewer should present PDFs as if the user has logged in. This is what happens with location-restricted media and images.

**Additional information**

I'm not sure how we can test this remotely. Whoever picks up the ticket may need to coordinate with Geoff if they need to see what the browser is doing when visiting PDF.

**To reproduce**

From an authorized location:

1. Visit [this purl](https://purl.stanford.edu/zs884sy8048).
2. See that the PDF is not available
3. Try this [Stacks link](https://stacks.stanford.edu/file/druid:zs884sy8048/GitaiKW_cover24_2.pdf): 
4. See that the PDF can be downloaded, which means the location-restriction is being applied to the file.

From outside an authorized location:

Follow the steps above and see that neither the PDF viewer nor the Stacks link will allow access to the PDF.

### PR DESCRIPTION
**Pull request by hudajkhan**
Closes #2360  

What this pull request does:

- Sets up a location restricted banner that is hidden when the page loads
- Changes the logic for when the viewer is available. It is now true unless the status for the first file is "not downloadable"
- Sets up  the file auth controller to check the location restriction message from stacks, and then show the location restriction banner and update the message to be the one returned from stacks

Note: This should work in staging, but the stacks changes will need to be pushed to production first for these embed changes to work in production

### CODE REVIEW

File: app/javascript/controllers/file_auth_controller.js [hunk 1]
```diff
@@ -264,4 +271,42 @@ export default class extends Controller {
...
+  }
+
+  // Checks the result of the probe auth request to see if access is restricted to location
+  // This code depends on the text returned by probe service, so changes to the heading
+  // should be reflected here as well.
+  isLocationRestricted(json) {
+    if(json.status == '401' && 'heading' in json && 'en' in json.heading && json.heading.en.length
+      && json.heading.en[0].startsWith('Content is restricted to location'))
+      return true
+    return false
```
Comment (jcoyne) [inline app/javascript/controllers/file_auth_controller.js:297]: can we do:
```suggestion
    return json.status == '401' && 'heading' in json && 'en' in json.heading && json.heading.en.length
      && json.heading.en[0].startsWith('Content is restricted to location')
```

Comment (jcoyne) [reply app/javascript/controllers/file_auth_controller.js:297]: I'm not sure we need to check `json.heading.en` or `json.heading.en.length` as we know our Stacks response will have these.

File: app/javascript/controllers/file_auth_controller.js [hunk 2]
```diff
@@ -264,4 +271,42 @@ export default class extends Controller {
...
+  extractRestrictedLocation(accessMessage) {
+    const probeServicePrefix = 'Content is restricted to location '
+    if(accessMessage != null && accessMessage.startsWith(probeServicePrefix))
+      return accessMessage.substring(probeServicePrefix.length, accessMessage.length)
+
+    return 'site visitors to the Stanford libraries'
+  }
+
+  retrieveRestrictedLocationMessage(json) {
+    return 'Access is restricted to the ' + this.extractRestrictedLocation(json.heading.en[0]) + '. See Access conditions for more information.'
```
Comment (jcoyne) [inline app/javascript/controllers/file_auth_controller.js:310]: Can this whole first sentence move to the IIIF Auth response heading in Stacks?

File: app/viewers/embed/viewer/document_viewer.rb [hunk 3]
```diff
@@ -27,15 +27,11 @@ def fullscreen?
...
-
-      # this indicates if the PDF is downloadable (though it could be stanford only)
-      # Stanford only and location restrictions are handled via a separate authorization flow,
-      # since it is possible for people to do something about the restriction
+      # This indicates if the first PDF is downloadable (though it could be stanford only)
+      # as well as location restricted.  Authorization for other documents will be
+      # checked as the user clicks on items in the content side bar.
       def available?
-        document_resource_files.first&.downloadable?
+        document_resource_files.first&.downloadable? || document_resource_files.first&.location_restricted?
```
Comment (jcoyne) [inline app/viewers/embed/viewer/document_viewer.rb:34]: I'm not sure why we're still checking this on the backend, since it looks like the frontend is also doing this check.

Comment (dnoneill) [reply app/viewers/embed/viewer/document_viewer.rb:34]: I think we keep doing as a patch because I don't think haven't added the JS to display this. this it should be `!document_resource_files.first&.no_download?` but yes I think we should be fixing this in another PR to the file_auth

File: app/javascript/controllers/file_auth_controller.js (hunk 2 above)
Comment (hudajkhan) [reply app/javascript/controllers/file_auth_controller.js:310]: I am working on that in a stacks PR, so I agree that would be better

File: app/viewers/embed/viewer/document_viewer.rb (hunk 3 above)
Comment (hudajkhan) [reply app/viewers/embed/viewer/document_viewer.rb:34]: I will leave a comment here to explain why. The code puts up a generic "content not available" block if it thinks the item is not available, hence this change to ensure an object that is not downloadable but is location restricted would not immediately display the content not available block.  @dnoneill I can try your suggestion if it covers all the cases, but that's the main motivation (to not show the content not available block)

File: app/javascript/controllers/file_auth_controller.js (hunk 2 above)
Comment (dnoneill) [reply app/javascript/controllers/file_auth_controller.js:310]: For now, so we can get this in because it is a blocker, can we just return what we are getting from stacks since it is very close to what we want and we can have the language update done after this is in?

File: app/javascript/controllers/file_auth_controller.js (hunk 1 above)
Comment (hudajkhan) [reply app/javascript/controllers/file_auth_controller.js:297]: yes to the first comment.  For the second comment, this is more to ensure if something weird happens on the response end, things don't just stop working.

File: app/viewers/embed/viewer/document_viewer.rb (hunk 3 above)
Comment (hudajkhan) [reply app/viewers/embed/viewer/document_viewer.rb:34]: I will use that logic then, thank you!

File: app/javascript/controllers/file_auth_controller.js (hunk 2 above)
Comment (hudajkhan) [reply app/javascript/controllers/file_auth_controller.js:310]: The other PR is merged so we should be good to go with the updated strings

File: app/components/pdf_component.html.erb [hunk 4]
```diff
@@ -9,6 +9,7 @@
 
   <% component.with_authorization_messages do %>
     <%= render LoginComponent.new %>
+    <%= render LocationRestrictionComponent.new %>
```
[the remark this answers is not in the document]
Comment (hudajkhan) [reply app/components/pdf_component.html.erb:12]: We just talked and agreed we can wait on that change until later, but that sounds like a good idea for subsequent work.

File: app/javascript/controllers/file_auth_controller.js [hunk 5]
```diff
@@ -259,4 +266,31 @@ export default class extends Controller {
...
     this.messagePanelTarget.hidden = true
   }
+
+  // To see if item is restricted by location, check the probe service json response
+  handleLocationRestricted(json, accessService) {
+    // The probe auth service is called for each file separately.
+    // If the location restriction target is available, then trigger auth denied message.
+    // The event will lead to the locked icon being displayed for this item
+    // This allows the lock window to show
+    const event = new CustomEvent('auth-denied', { accessService: accessService })
```
Comment (jcoyne) [inline app/javascript/controllers/file_auth_controller.js:276]: I think we should stuff the location restricted message in this event.  Then we can have a controller devoted to displaying these messages, and this controller would not have to deal with this

Comment (jcoyne) [reply app/javascript/controllers/file_auth_controller.js:276]: This can be a follow-on PR though.

File: app/viewers/embed/viewer/document_viewer.rb [hunk 6]
```diff
@@ -27,15 +27,11 @@ def fullscreen?
...
-
-      # this indicates if the PDF is downloadable (though it could be stanford only)
-      # Stanford only and location restrictions are handled via a separate authorization flow,
-      # since it is possible for people to do something about the restriction
+      # This indicates if the first PDF is downloadable (though it could be stanford only)
+      # as well as location restricted.  Authorization for other documents will be
+      # checked as the user clicks on items in the content side bar.
       def available?
-        document_resource_files.first&.downloadable?
+        !document_resource_files.first&.no_download?
```
Comment (jcoyne) [inline app/viewers/embed/viewer/document_viewer.rb:34]: I'm still not clear on why we need this at all.  Can't we just run this all through the IIIF auth?

Comment (hudajkhan) [reply app/viewers/embed/viewer/document_viewer.rb:34]: The PDF Component html will not show the viewer at all if the "viewer.available?" is false.  Instead, it will just show a "content not available" section.  This change ensures the content not available section is not displayed unless the first file is a "no download" option. If we want to change that logic, I'd suggest tackling that in a different issue because there is probably more to streamline here (or to work out).

File: app/javascript/controllers/file_auth_controller.js (hunk 5 above)
Comment (hudajkhan) [reply app/javascript/controllers/file_auth_controller.js:276]: I think that approach makes sense and it would be fine to do in a follow up PR. @dnoneill and I were also discussing the other cases (embargo etc.) so it makes sense to have that logic in its own event/controller framework.

**Review by jcoyne — APPROVED** [review]
