### PR TITLE
Use default thumbnail for media if dataset thumbnail URL is blank

### LINKED ISSUE #1640: Broken image in right drawer when there is no thumbnail
Seen in https://embed-stage.stanford.edu/iframe?new_component=true&url=https://sul-purl-stage.stanford.edu/nr582tm3161&_v=1698775996
Screenshot 2023-10-31 at 2 23 53 PM

### PR DESCRIPTION
**Pull request by mjgiarlo**
Not just an empty string.

Fixes #1640

Screenshot from 2023-11-03 11-14-59

### CODE REVIEW

File: app/javascript/src/modules/media_thumbnail_builder.js [hunk 1]
```diff
@@ -9,7 +9,7 @@ export default function(dataset, index) {
     }
 
     let thumbnailIcon = '';
-    if (dataset.thumbnailUrl !== '') {
+    if (dataset.thumbnailUrl && dataset.thumbnailUrl !== '') {
```
Comment (mjgiarlo) [inline app/javascript/src/modules/media_thumbnail_builder.js:12]: The bug here was that the `img@src` attr below was being set to `undefined` because the check above only looks at whether `thumbnailUrl` is an empty string, not if it's defined.

If folks prefer that this bug should be fixed upstream of this code, holler at me.

Comment (jcoyne) [reply app/javascript/src/modules/media_thumbnail_builder.js:12]: Yes, I'm wondering why it wasn't defined. I think we should track that down too.

Comment (mjgiarlo) [reply app/javascript/src/modules/media_thumbnail_builder.js:12]: @jcoyne Will do

Comment (mjgiarlo) [reply app/javascript/src/modules/media_thumbnail_builder.js:12]: @jcoyne When the file has no thumbnail (when `file.thumbnail` is falsey), `file_thumb` is set to `nil` here: https://github.com/sul-dlss/sul-embed/blob/db08304bd05e518bfe11bd0495b6108b13e369ef/app/components/embed/media_tag_component.rb#L37

**Comment by jcoyne** [comment]
This also doesn't feel like the design is right.  I was thinking this icon should stretch to fill the area that would have been occupied by the thumbnail if it were present. Can you add that?

File: app/javascript/src/modules/media_thumbnail_builder.js (hunk 1 above)
Comment (jcoyne) [reply app/javascript/src/modules/media_thumbnail_builder.js:12]: okay, so `data: { thumbnail_url: nil }` ends up not generating any attribute, thus we need to do the check on `dataset.thumbnailUrl`

Comment (jcoyne) [reply app/javascript/src/modules/media_thumbnail_builder.js:12]: How about we switch it to `data: { thumbnail_url: @thumbnail.presence }` and then we can drop the empty string check in the javascript?

Comment (mjgiarlo) [reply app/javascript/src/modules/media_thumbnail_builder.js:12]: Sounds good, as I don't think it's ever finding the empty string now.

**Comment by mjgiarlo** [comment]
@jcoyne 💬 
> This also doesn't feel like the design is right. I was thinking this icon should stretch to fill the area that would have been occupied by the thumbnail if it were present. Can you add that?

This is an icon from the sul_styles icon font, I think? I've tried mucking with `width` and `height` but they are invalid properties in this context. I can make the icon larger by choosing `font-size: xxx-large` but it doesn't fill the space. If you have CSS advice or want to pair on this, I'm all ears.

**Comment by jcoyne** [comment]
@mjgiarlo have you tried something like `font-size: 52px`?

**Comment by jcoyne** [comment]
@mjgiarlo I think a px value makes sense here because we're matching to an image thumbnail that has a particular px value.

**Comment by mjgiarlo** [comment]
@jcoyne Just pushed up the change with an updated screenshot ☝🏻

**Review by jcoyne — APPROVED** [review]
Thanks @mjgiarlo . I appreciate all the changes. 🙇
